build:
  project: HelloWorld.sln  
deploy:
  release: myproduct-v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: fKZuOrs5MJEuob+GBNYhsnasaeiRrsKjGxtIvffInvdKDl/uKXPI6cELRRnTR/5Y
    artifact: bin\Debug\*.exe        
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: false        # deploy on tag push only