build:
  project: HelloWorld.sln  
deploy:
  release: v$(appveyor_build_version)
  description: 'Release description'
  provider: GitHub
  auth_token:
    secure: fKZuOrs5MJEuob+GBNYhsnasaeiRrsKjGxtIvffInvdKDl/uKXPI6cELRRnTR/5Y
    artifact: bin\Debug\*.exe        
