version: 1.0.{build}
build:
  project: HelloWorld.sln
  verbosity: minimal
artifacts:
- path: bin\Debug\*.exe
deploy:
- provider: GitHub
  auth_token:
    secure: stRZU6MIr0ug18n/lVxLLvw7u8h8tKSoTRD3qdp+HUqWRD+LI8mBrOOawcYqsX3oxV3b2x+Pi7qZs8m/V7fE5Qb58jk4aKOysL2iyYsOKII=
  artifact: bin\Debug\HelloWorld.exe